Feature/database structure
gchilczuk/questor pull request #3
Opened 2018-07-07 18:17 UTC by gchilczuk

It's not ready yet, but I want to have an overall look.

2018-07-11 19:28 UTC, marwaw requested changes
- think about develop branch
- make better documentation

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +class Edition(models.Model):
I don't get the name :|

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +    correctly answer the final question of the question.
`of the quest`

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +    """
Missing fields description

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +    edition = models.ForeignKey(Edition, models.CASCADE, related_name='quests', related_query_name='quest')
It's easier to read if you add key-word arguments

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +    content = models.CharField(max_length=24)
content or answer?

2018-07-11 19:28 UTC, marwaw commented on game/models.py
> +        Evaluate if answer provided by user is correct and return appropriate answer
proper answer sounds better

2018-07-11 19:28 UTC, marwaw commented on game/tests/conftest.py
> +    return Reward.objects.create(description='The cake is a lie.')
get_or_create

2018-07-11 19:28 UTC, marwaw commented on game/tests/conftest.py
> +            for _ in range(2)]
Two the same sample answers

2018-07-19 18:53 UTC, gchilczuk commented on game/models.py
> +class Edition(models.Model):
I don't have a better idea how to name it :/

2018-07-19 19:14 UTC, gchilczuk commented on game/models.py
> +    content = models.CharField(max_length=24)
I don't like when the object `Answer` has an attribute called `answer`.  I don't have any better name

2018-07-21 09:30 UTC, merged